name: yts-scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script # run
        run: |
          cd ~/
          ls
          python ./yts_mx_api.py
        
      - name: execute py script # run
        run: python ./linkdownload.py
