name: yts-scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: check dir
        run: |
          pwd
          ls
          
      - name: execute py script # run
        run:
          python yts_mx_api.py
        
      - name: execute py script # run
        run: python ./linkdownload.py
